#define LOG_TO_SD
#define LOG_LEVEL LOG_LEVEL_INFO

#define PIN_SD_CS GPIO_NUM_5

#define PIN_I2S_BCK GPIO_NUM_26
#define PIN_I2S_WC GPIO_NUM_22
#define PIN_I2S_DATA GPIO_NUM_25

#define PIN_RFID_IRQ GPIO_NUM_34
#define PIN_RFID_CS GPIO_NUM_15

#define PIN_MCP23S17_CS GPIO_NUM_27
#define PIN_MCP23S17_IRQ GPIO_NUM_4

#define PIN_POWER GPIO_NUM_21
#define PIN_WAKEUP GPIO_NUM_33

#define PIN_AMP_ENABLE_MCP 7
#define PIN_MFRC522_RESET_MCP 3

#define PIN_LED_RED_MCP 6
#define PIN_LED_GREEN_MCP 5
#define PIN_LED_BLUE_MCP 4
#define PIN_LED GPIO_NUM_0
#define COMMON_ANODE 1

#define DIP_SWITCH_SHIFT 6
#define TP5400_STATUS_SHIFT 0

#define POWER_ON_DELAY 50

#define SPI_FREQ_SD 80000000
#define HSPI_FREQ 10000000

#define PLAYBACK_CHUNK_SIZE 1024
#define PLAYBACK_QUEUE_SIZE 8
#define SAMPLE_RATE 44100

#define AUDIO_CORE 1
#define SERVICE_CORE 0
#define CPU_FREQUENCY 160

#define TASK_PRIORITY_I2S 50
#define TASK_PRIORITY_AUDIO 10
#define TASK_PRIORITY_RFID 20
#define TASK_PRIORITY_GPIO 10
#define TASK_PRIORITY_WATCHDOG 1
#define TASK_PRIORITY_LED 5
#define TASK_PRIORITY_POWER 1
#define TASK_PRIORITY_NET 1

#define STACK_SIZE_I2S 0x0800
#define STACK_SIZE_AUDIO 0x8000
#define STACK_SIZE_RFID 0x1000
#define STACK_SIZE_GPIO 0x0800
#define STACK_SIZE_WATCHDOG 0x0800
#define STACK_SIZE_LED 0x0800
#define STACK_SIZE_POWER 0x0800
#define STACK_SIZE_NET 0x1000

#define DEBOUNCE_DELAY 50

#define BTN_PAUSE_MASK 0x01
#define BTN_VOLUME_DOWN_MASK 0x02
#define BTN_VOLUME_UP_MASK 0x04
#define BTN_PREVIOUS_MASK 0x08
#define BTN_NEXT_MASK 0x10

#define BTN_POWEROFF_DELAY 2000
#define BTN_REWIND_DELAY 1000
#define BTN_VOLUME_REPEAT 500
#define BTN_NEXT_REPEAT 1000

#define REWIND_TIMEOUT 500

#define VOLUME_STEP 10
#define VOLUME_LIMIT 100
#define VOLUME_FULL 100
#define VOLLUME_DEFAULT 20

#define WATCHDOG_TIMEOUT_SECONDS 180

#define VOLTAGE_CORRECTION_MV 120

#define THRESHOLD_BATTERY_LOW_MV 3600
#define THRESHOLD_BATTERY_CRITICAL_MV 3500
#define THRESHOLD_BATTERY_POWEROFF_MV 3400
#define BATTERY_LEVEL_HYSTERESIS_MV 100
#define POWER_POLL_INTERVAL 1000
